### ISSUE TITLE
update to the latest sources

### ISSUE THREAD

**Issue by DH1KLM** [ew8bak/pihpsdr#1]
Not an issue per se. 
Is there a way to update this repository to the latest sources from https://github.com/dl1ycf/pihpsdr or https://github.com/n1gp/pihpsdr?

**Comment by ew8bak** [comment]
I will try

**Comment by ew8bak** [comment]
> Not an issue per se. Is there a way to update this repository to the latest sources from https://github.com/dl1ycf/pihpsdr or https://github.com/n1gp/pihpsdr?

https://github.com/ew8bak/dl1ycf_pihpsdr

The project compiles and runs, but there is a problem with audio buffer overflow. Maybe someone can help?

**Comment by DH1KLM** [comment]
Hello Vladimir,
Could you please explain to me how I can port the current sources from https://github.com/dl1ycf/pihpsdr to windows like you did.
Maybe the audio buffer problem is solved in the meantime.

**Comment by ew8bak** [comment]
I don't think it's been resolved because... This problem only occurs under Windows. I didn't have time to solve this problem. As we see, no one can or wants to help. A little later I will return to this project and update the code to the latest from https://github.com/dl1ycf/pihpsdr
Everything will be here https://github.com/ew8bak/dl1ycf_pihpsdr
Better write to that repository

**Comment by DH1KLM** [comment]
ok, thank you.
